import { PresetRoster } from '../types/seating';

export const PRESET_ROSTERS: PresetRoster[] = [
  {
    id: 'sija-10-a',
    name: 'Kelas 10 SIJA A (36 Absen)',
    category: 'SMK',
    students: [
      'Absen 1',
      'Absen 2',
      'Absen 3',
      'Absen 4',
      'Absen 5',
      'Absen 6',
      'Absen 7',
      'Absen 8',
      'Absen 9',
      'Absen 10',
      'Absen 11',
      'Absen 12',
      'Absen 13',
      'Absen 14',
      'Absen 15',
      'Absen 16',
      'Absen 17 [Prioritas]',
      'Absen 18',
      'Absen 19',
      'Absen 20 [Prioritas]',
      'Absen 21',
      'Absen 22 [Prioritas]',
      'Absen 23',
      'Absen 24',
      'Absen 25',
      'Absen 26',
      'Absen 27',
      'Absen 28 [Prioritas]',
      'Absen 29',
      'Absen 30',
      'Absen 31 [Prioritas]',
      'Absen 32',
      'Absen 33',
      'Absen 34',
      'Absen 35',
      'Absen 36 [Prioritas]',
    ],
    recommendedConfig: {
      title: 'Kelas 10 SIJA A',
      teacherName: 'Hartitik, S.Pd',
      roomNumber: 'Lab SIJA',
      rows: 5,
      cols: 8,
      arrangement: '2-2',
      prioritizeMinusInFront: true,
    },
  },
];
